import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/navbar";
import LandingPage from "@/components/landing-page";
import About from "@/components/about";
import { Container } from "@mui/material";
import SliderComponent from "@/components/home-slider";
import MobileApplication from "@/components/mobile-application";
import Service from "@/components/service";
import Payments from "@/components/payments";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Food Food</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <LandingPage />
        <Container maxWidth="xl" sx={{ my: 5 }}>
          <About />
          <SliderComponent />
          <MobileApplication />
          <Service />
          <Payments />
        </Container>
      </div>
    </>
  );
}
